#!/bin/sh
#
# sorts and remove duplicate lines in a file
usage='
USAGE
sort_inplace File'

if [ $# != 1 ]; then
     echo $usage
     exit 1
else
     filename=$1
     tmp_file="$1"_sorttmp
     sort $filename > $tmp_file
     uniq $tmp_file > $filename
fi
exit 0

